name: Build CoreProtect Plugin
on:
  push:
    branches:
      - development # Change this to your preferred branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Build with Maven
        run: mvn clean package -Dbranch=development

      - name: Upload JAR as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: coreprotect-plugin
          path: target/*.jar
